<a href="https://colab.research.google.com/github/piyush-raj04/Python/blob/main/Pandas_working_with_XML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Pandas working with xml file

In [4]:
import pandas as pd

pd.read_xml('test.xml')

      shape  degrees  sides
0    square      360    4.0
1    circle      360    NaN
2  triangle      180    3.0

In [11]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data xmlns="http://example.com">
 <row>
   <shape>square</shape>
   <degrees>360</degrees>
   <sides>4.0</sides>
   <firstname>Piyush</firstname>
 </row>
 <row>
   <shape>circle</shape>
   <degrees>360</degrees>
   <sides/>
   <firstname/>
 </row>
 <row>
   <shape>triangle</shape>
   <degrees>180</degrees>
   <sides>3.0</sides>
   <firstname/>
 </row>
</data>'''

In [12]:
pd.read_xml(xml)

/tmp/ipykernel_4828/2704978085.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml)

      shape  degrees  sides firstname
0    square      360    4.0    Piyush
1    circle      360    NaN      None
2  triangle      180    3.0      None

In [15]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data>
  <row shape="square" degrees="360" sides="4.0" firstname="Piyush"/>
  <row shape="circle" degrees="360"/>
  <row shape="triangle" degrees="180" sides="3.0" lastname="Raj"/>
</data>'''

In [16]:
pd.read_xml(xml,xpath=".//row")

/tmp/ipykernel_4828/2888431730.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml,xpath=".//row")

      shape  degrees  sides firstname lastname
0    square      360    4.0    Piyush     None
1    circle      360    NaN      None     None
2  triangle      180    3.0      None      Raj

In [17]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<doc:data xmlns:doc="https://example.com">
  <doc:row>
    <doc:shape>square</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides>4.0</doc:sides>
  </doc:row>
  <doc:row>
    <doc:shape>circle</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides/>
  </doc:row>
  <doc:row>
    <doc:shape>triangle</doc:shape>
    <doc:degrees>180</doc:degrees>
    <doc:sides>3.0</doc:sides>
  </doc:row>
</doc:data>'''

In [22]:
df=pd.read_xml(xml,xpath=".//doc:row",namespaces={"doc": "https://example.com"})

/tmp/ipykernel_4828/1616642587.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_xml(xml,xpath=".//doc:row",namespaces={"doc": "https://example.com"})

In [23]:
df.to_xml('test1.xml')