<a href="https://colab.research.google.com/github/piyush-raj04/Python/blob/main/Python_Pickling_and_Unpickling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python picking and Unpicking

In [1]:
import seaborn as sns

In [2]:
df=sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
import pickle

In [5]:
filename='file.pkl'

In [6]:
##serialize process
pickle.dump(df,open(filename,'wb'))

In [7]:
## unserialize process
df1=pickle.load(open(filename,'rb'))

In [9]:
type(df1)

pandas.core.frame.DataFrame

In [10]:
df1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
dic_example={'first_name':'Piyush','last_name':'Raj'}

In [12]:
pickle.dump(dic_example,open('test.pkl','wb'))